ksdjf

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -6,22 +6,50 @@ on:
       - '*'
       - '!main'
 
-jobs:
-apply:
+env:
+  WORKING_DIR: './base'
+  TF_LOG: INFO
+  TF_INPUT: false
+
+jobs: 
+  check-code:
     runs-on: ubuntu-latest
     defaults:
-    run:
-        working-directory: ${{ env.tf_actions_working_dir }}
+      run:
+        working-directory: ${{ env.WORKING_DIR }}
+
     steps:
-    - uses: actions/checkout@v4
-    
-    - uses: hashicorp/setup-terraform@v3
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v3
 
+    # Install the selected version of Terraform CLI 
+    - name: Setup Terraform
+      uses: hashicorp/setup-terraform@v2
+      with:
+        terraform_version: ${{ secrets.TERRAFORM_VERSION }}
+
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
-    id: init
-    run: terraform init
+      id: init
+      env:
+        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
+        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
+        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
+        STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
+        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
+      run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"
 
-    - name: Terraform Apply
-    run: terraform apply -auto-approve
-    env:
-        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
+    # Run a terraform fmt to check syntax
+    - name: Terraform Format
+      id: fmt
+      run: terraform fmt -check
+
+    # Run a terraform validate
+    - name: Terraform Validate
+      id: validate
+      # Run even if formatting fails
+      if: success() || failure()
+      run: terraform validate -no-color
